/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.isu.cs.cs2263.hw02;

import java.util.StringTokenizer;

public class Library<E> implements PushbackTokenizer<E> {
    private StringTokenizer i = new StringTokenizer();

    @Override
    public String nextToken() {
        return  i.nextToken();
    }


    @Override
    public boolean hasMoreTokens() {
        return i.hasMoreTokens();
    }

    @Override
    public void pushback() {

    }

    public boolean someLibraryMethod() {
        return false;
    }
}
